// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElLoading: typeof import('element-plus/es')['ElLoading']
  const ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
}
export {}
